//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dvd
    {
        public int DvdId { get; set; }
        public string Title { get; set; }
        public int DvdNumber { get; set; }
        public Nullable<bool> Available { get; set; }
        public decimal Price { get; set; }
        public Genres Genre { get; set; }
        public Nullable<int> RentId { get; set; }
    
        public virtual Rent Rent { get; set; }
    }
}
