//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore
{
    using System;
    
    public enum Genres : int
    {
        Action = 1,
        Comedy = 2,
        Documentary = 3,
        Horror = 4,
        Thriller = 5,
        Fantasy = 6,
        Sport = 7
    }
}
